-- DESCONECTA TODOS OS USUARIOS DE UM BANCO POSTGRES
SELECT PID, BACKEND_START, WAIT_EVENT_TYPE, PG_TERMINATE_BACKEND(PID) FROM PG_STAT_ACTIVITY WHERE PID <> PG_BACKEND_PID();

-- EXCLUI BANCO DE DADOS
DROP DATABASE DYSPROSIUM_DESENVOLVIMENTO;

-- CRIAR BANCO DE DADOS (DESENVOLVIMENTO)
CREATE DATABASE dbd_plfind;

-- CRIAR BANCO DE DADOS (TESTE)
CREATE DATABASE dbt_plfind;

-- CRIAR BANCO DE DADOS (HOMOLOGACAO)
CREATE DATABASE dbh_plfind;

-- CRIAR BANCO DE DADOS (PRODUCAO)
CREATE DATABASE dbp_plfind;

-- EXCLUIR TABELA
DROP TABLE TB_DESPESA_VARIAVEL;

-- EXCLUIR SEQUENCE
DROP SEQUENCE PUBLIC.SEQUENCE_TB_DESPESA_VARIAVEL;

-- CRIAR SEQUENCE
CREATE SEQUENCE PUBLIC.SEQUENCE_TB_DESPESA_VARIAVEL;

-- CRIAR TABELA
CREATE TABLE PUBLIC.TB_DESPESA_VARIAVEL(
	CODIGO										INTEGER 				NOT NULL 			DEFAULT			NEXTVAL('SEQUENCE_TB_DESPESA_VARIAVEL'::REGCLASS),
	ID_FAVORECIDO								INTEGER					NOT NULL,
	ID_ITEM_DESPESA								INTEGER					NOT NULL,
	ID_FORMA_PAGAMENTO							INTEGER					NOT NULL,
	ID_PRODUTO_SERVICO							INTEGER					NOT NULL,
	ID_FONTE_PAGAMENTO							INTEGER					NOT NULL,
	ID_CANAL_PAGAMENTO							INTEGER					NOT NULL,
	ID_RESPONSAVEL_PAGAMENTO					INTEGER					NOT NULL,
	VALOR_DESPESA								VARCHAR(60)				NOT NULL,
	DATA_DESPESA								VARCHAR(60)				NOT NULL,
	QUANTIDADE_ITEM_DESPESA						INTEGER						NULL,
	IS_FONTE_PAGAMENTO_UNICO					BOOLEAN					NOT NULL,
	IS_ITEM_UNICO								BOOLEAN					NOT NULL,
	OBSERVACAO									VARCHAR(255)				NULL
) WITH ( OIDS = FALSE );

-- CRIAR COMENTARIOS
COMMENT ON TABLE 	PUBLIC.TB_DESPESA_VARIAVEL.CODIGO 						IS 'IDENTIFICADOR UNICO DA TABELA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_FAVORECIDO 				IS 'CHAVE ESTRANGEIRA DA TABELA TB_PESSOA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_ITEM_DESPESA				IS 'CHAVE ESTRANGEIRA DA TABELA TB_ITEM_DESPESA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_FORMA_PAGAMENTO 			IS 'CHAVE ESTRANGEIRA DA TABELA TB_FORMA_PAGAMENTO';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_PRODUTO_SERVICO 			IS 'CHAVE ESTRANGEIRA DA TABELA TB_PRODUTO_SERVICO';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_FONTE_PAGAMENTO 			IS 'CHAVE ESTRANGEIRA DA TABELA TB_FONTE_PAGAMENTO';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_CANAL_PAGAMENTO 			IS 'CHAVE ESTRANGEIRA DA TABELA TB_CANAL_PAGAMENTO';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_RESPONSAVEL_PAGAMENTO 	IS 'CHAVE ESTRANGEIRA DA TABELA TB_RESPONSAVEL_PAGAMENTO';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.VALOR_DESPESA 				IS 'REFERE-SE AO VALOR UNITARIO DE UMA DETERMINADA DESPESA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.DATA_DESPESA 				IS 'REFERE-SE A DATA DE REALIZACAO DA DESPESA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.QUANTIDADE_ITEM_DESPESA		IS 'REFERE-SE A QUANTIDADE DE ITENS DE UMA DESPESA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.IS_FONTE_PAGAMENTO_UNICO		IS 'INDICA SE A FONTE DE PAGAMENTO E UNICA, OU SEJA, SE A COMPRA FOI COMPARTILHADA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.IS_ITEM_UNICO				IS 'INDICA SE A O ITEM E UNICO';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.OBSERVACAO					IS 'GUARDA AS OBSERVACOES (SE HOUVEREM)';
