-- DESCONECTA TODOS OS USUARIOS DE UM BANCO POSTGRES
SELECT PID, BACKEND_START, WAIT_EVENT_TYPE, PG_TERMINATE_BACKEND(PID) FROM PG_STAT_ACTIVITY WHERE PID <> PG_BACKEND_PID();

-- EXCLUI BANCO DE DADOS
DROP DATABASE DYSPROSIUM_DESENVOLVIMENTO;

-- CRIAR BANCO DE DADOS (DESENVOLVIMENTO)
CREATE DATABASE dbd_plfind;

-- CRIAR BANCO DE DADOS (TESTE)
CREATE DATABASE dbt_plfind;

-- CRIAR BANCO DE DADOS (HOMOLOGACAO)
CREATE DATABASE dbh_plfind;

-- CRIAR BANCO DE DADOS (PRODUCAO)
CREATE DATABASE dbp_plfind;

-- EXCLUIR TABELA
DROP TABLE TB_DESPESA_VARIAVEL;

-- EXCLUIR SEQUENCE
DROP SEQUENCE PUBLIC.SEQUENCE_TB_DESPESA_VARIAVEL;

-- CRIAR SEQUENCE
CREATE SEQUENCE PUBLIC.SEQUENCE_TB_DESPESA_VARIAVEL;

-- CRIAR TABELA
CREATE TABLE PUBLIC.TB_DESPESA_VARIAVEL(
	CODIGO										INTEGER 				NOT NULL 			DEFAULT			NEXTVAL('SEQUENCE_TB_DESPESA_VARIAVEL'::REGCLASS),
	ID_FAVORECIDO								INTEGER					NOT NULL,
	ID_ITEM_DESPESA								INTEGER					NOT NULL,
	ID_FORMA_PAGAMENTO							INTEGER					NOT NULL,
	ID_PRODUTO_SERVICO							INTEGER					NOT NULL,
	ID_FONTE_PAGAMENTO							INTEGER					NOT NULL,
	ID_CANAL_PAGAMENTO							INTEGER					NOT NULL,
	ID_RESPONSAVEL_PAGAMENTO					INTEGER					NOT NULL,
	VALOR_DESPESA								VARCHAR(60)				NOT NULL,
	DATA_DESPESA								VARCHAR(60)				NOT NULL,
	QUANTIDADE_ITEM_DESPESA						INTEGER						NULL,
	IS_FONTE_PAGAMENTO_UNICO					BOOLEAN					NOT NULL,
	IS_ITEM_UNICO								BOOLEAN					NOT NULL,
	OBSERVACAO									VARCHAR(255)				NULL
) WITH ( OIDS = FALSE );

-- CRIAR COMENTARIOS
COMMENT ON TABLE 	PUBLIC.TB_DESPESA_VARIAVEL.CODIGO 						IS 'IDENTIFICADOR UNICO DA TABELA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_FAVORECIDO 				IS 'CHAVE ESTRANGEIRA DA TABELA TB_PESSOA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_ITEM_DESPESA				IS 'CHAVE ESTRANGEIRA DA TABELA TB_ITEM_DESPESA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_FORMA_PAGAMENTO 			IS 'CHAVE ESTRANGEIRA DA TABELA TB_FORMA_PAGAMENTO';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_PRODUTO_SERVICO 			IS 'CHAVE ESTRANGEIRA DA TABELA TB_PRODUTO_SERVICO';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_FONTE_PAGAMENTO 			IS 'CHAVE ESTRANGEIRA DA TABELA TB_FONTE_PAGAMENTO';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_CANAL_PAGAMENTO 			IS 'CHAVE ESTRANGEIRA DA TABELA TB_CANAL_PAGAMENTO';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.ID_RESPONSAVEL_PAGAMENTO 	IS 'CHAVE ESTRANGEIRA DA TABELA TB_RESPONSAVEL_PAGAMENTO';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.VALOR_DESPESA 				IS 'REFERE-SE AO VALOR UNITARIO DE UMA DETERMINADA DESPESA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.DATA_DESPESA 				IS 'REFERE-SE A DATA DE REALIZACAO DA DESPESA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.QUANTIDADE_ITEM_DESPESA		IS 'REFERE-SE A QUANTIDADE DE ITENS DE UMA DESPESA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.IS_FONTE_PAGAMENTO_UNICO		IS 'INDICA SE A FONTE DE PAGAMENTO E UNICA, OU SEJA, SE A COMPRA FOI COMPARTILHADA';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.IS_ITEM_UNICO				IS 'INDICA SE A O ITEM E UNICO';
COMMENT ON COLUMN 	PUBLIC.TB_DESPESA_VARIAVEL.OBSERVACAO					IS 'GUARDA AS OBSERVACOES (SE HOUVEREM)';

-- DML 
SELECT * FROM PUBLIC.TABLE_CANAL_PAGAMENTO;
SELECT * FROM PUBLIC.TABLE_FAVORECIDO;
SELECT * FROM PUBLIC.TABLE_FONTE_PAGAMENTO;
SELECT * FROM PUBLIC.TABLE_PRODUTO_SERVICO;
SELECT * FROM PUBLIC.TABLE_RESPONSAVEL_PAGAMENTO;
SELECT * FROM PUBLIC.TABLE_DESPESA_VARIAVEL;

INSERT INTO PUBLIC.TABLE_FAVORECIDO VALUES(NEXTVAL('SEQUENCE_FAVORECIDO'), 'SUPERMERCADO PRAVOCE (TAGUATINGA NORTE)');
INSERT INTO PUBLIC.TABLE_CANAL_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_CANAL_PAGAMENTO'), TRUE, 'PAGAMENTO EM CAIXA');
INSERT INTO PUBLIC.TABLE_FONTE_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_FONTE_PAGAMENTO'), TRUE, 'BANCO SANTANDER S.A');
INSERT INTO PUBLIC.TABLE_PRODUTO_SERVICO VALUES(NEXTVAL('SEQUENCE_PRODUTO_SERVICO'), 'MOUSE OPTICO (SEM FIO) MULTILASER');
INSERT INTO PUBLIC.TABLE_RESPONSAVEL_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_RESPONSAVEL_PAGAMENTO'), TRUE, TRUE, TRUE, 'JOSE QUINTINN');

DELETE FROM PUBLIC.TB_DESPESA_VARIAVEL WHERE CODIGO IS NOT NULL;

SELECT * FROM PUBLIC.TABLE_CANAL_PAGAMENTO;
SELECT * FROM PUBLIC.TABLE_FAVORECIDO;
SELECT * FROM PUBLIC.TABLE_FONTE_PAGAMENTO;
SELECT * FROM PUBLIC.TABLE_FORMA_PAGAMENTO;
SELECT * FROM PUBLIC.TABLE_PRODUTO_SERVICO;
SELECT * FROM PUBLIC.TABLE_RESPONSAVEL_PAGAMENTO;
SELECT * FROM PUBLIC.TABLE_DESPESA_VARIAVEL;

INSERT INTO PUBLIC.TABLE_FAVORECIDO VALUES(NEXTVAL('SEQUENCE_FAVORECIDO'), 'SUPERMERCADO PRAVOCE (TAGUATINGA NORTE)');
INSERT INTO PUBLIC.TABLE_FAVORECIDO VALUES(NEXTVAL('SEQUENCE_FAVORECIDO'), 'SÓ DIGITAL COMÉRCIO E SERVIÇO DE INFORMÁTICA (PLANO PILOTO)');
INSERT INTO PUBLIC.TABLE_FAVORECIDO VALUES(NEXTVAL('SEQUENCE_FAVORECIDO'), 'SUPERMERCADO VENEZA (TAGUANTIGA QNJ)');
INSERT INTO PUBLIC.TABLE_FAVORECIDO VALUES(NEXTVAL('SEQUENCE_FAVORECIDO'), 'UBER TECNOLOGIA (NACIONAL)');
INSERT INTO PUBLIC.TABLE_CANAL_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_CANAL_PAGAMENTO'), TRUE, 'PAGAMENTO EM CAIXA');
INSERT INTO PUBLIC.TABLE_CANAL_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_CANAL_PAGAMENTO'), TRUE, 'PAGAMENTO VIA INTERNET BANKING');
INSERT INTO PUBLIC.TABLE_CANAL_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_CANAL_PAGAMENTO'), TRUE, 'PAGAMENTO VIA APLICATIVO');
INSERT INTO PUBLIC.TABLE_CANAL_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_CANAL_PAGAMENTO'), TRUE, 'PAGAMENTO VIA BOLETO BANCÁRIO');
INSERT INTO PUBLIC.TABLE_CANAL_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_CANAL_PAGAMENTO'), TRUE, 'PAGAMENTO VIA CHEQUE PREDATADO');
INSERT INTO PUBLIC.TABLE_FONTE_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_FONTE_PAGAMENTO'), TRUE, 'BANCO SANTANDER S.A - CARTÃO DE CRÉDITO (XXXX XXXX XXXX YYYY)');
INSERT INTO PUBLIC.TABLE_FONTE_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_FONTE_PAGAMENTO'), TRUE, 'CONTA CARTEIRA');
INSERT INTO PUBLIC.TABLE_FONTE_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_FONTE_PAGAMENTO'), TRUE, 'ALELO (CARTÃO ALIMENTAÇÃO)');
INSERT INTO PUBLIC.TABLE_FONTE_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_FONTE_PAGAMENTO'), TRUE, 'BANCO NUBANK - CARTÃO DE CRÉDITO (XXXX XXXX XXXX 1928)');
INSERT INTO PUBLIC.TABLE_PRODUTO_SERVICO VALUES(NEXTVAL('SEQUENCE_PRODUTO_SERVICO'), 'MOUSE OPTICO (SEM FIO) MULTILASER');
INSERT INTO PUBLIC.TABLE_RESPONSAVEL_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_RESPONSAVEL_PAGAMENTO'), TRUE, TRUE, TRUE, 'JOSE QUINTINN');
INSERT INTO PUBLIC.TABLE_RESPONSAVEL_PAGAMENTO VALUES(NEXTVAL('SEQUENCE_RESPONSAVEL_PAGAMENTO'), TRUE, TRUE, TRUE, 'JAMILLE ALVES');

DELETE FROM PUBLIC.TABLE_DESPESA_VARIAVEL WHERE CODIGO IS NOT NULL;
DELETE FROM PUBLIC.TABLE_PRODUTO_SERVICO WHERE CODIGO IS NOT NULL;
DELETE FROM PUBLIC.TABLE_CANAL_PAGAMENTO WHERE CODIGO IS NOT NULL;
DELETE FROM PUBLIC.TABLE_RESPONSAVEL_PAGAMENTO WHERE CODIGO IS NOT NULL;
DELETE FROM PUBLIC.TABLE_FAVORECIDO WHERE CODIGO IS NOT NULL;
DELETE FROM PUBLIC.TABLE_FORMA_PAGAMENTO WHERE CODIGO IS NOT NULL;
DELETE FROM PUBLIC.TABLE_FONTE_PAGAMENTO WHERE CODIGO IS NOT NULL;

-- RECUPERAR DESPESAS VARIAVEIS
SELECT 
	TABLE_DESPESA_VARIAVEL_.CODIGO AS CODIGO,
	TABLE_FAVORECIDO_.NOME AS FAVORECIDO,
	TABLE_DESPESA_VARIAVEL_.DATA_DESPESA AS DATA_,
	TABLE_PRODUTO_SERVICO_.DESCRICAO AS PRODUTO,
	TABLE_DESPESA_VARIAVEL_.VALOR_TOTAL_DESPESA AS VALOR,
	TABLE_FONTE_PAGAMENTO_.NOME AS FORMA_PAGAMENTO,
	TABLE_CANAL_PAGAMENTO_.NOME AS CANAL_PAGAMENTO,
	TABLE_RESPONSAVEL_PAGAMENTO_.NOME AS RESPONSAVEL_PAGAMENTO,
	TABLE_DESPESA_VARIAVEL_.OBSERVACAO AS OBSERVACAO
FROM PUBLIC.TABLE_DESPESA_VARIAVEL TABLE_DESPESA_VARIAVEL_
JOIN PUBLIC.TABLE_FAVORECIDO TABLE_FAVORECIDO_ ON TABLE_FAVORECIDO_.CODIGO = TABLE_DESPESA_VARIAVEL_.ID_FAVORECIDO
JOIN PUBLIC.TABLE_PRODUTO_SERVICO TABLE_PRODUTO_SERVICO_ ON TABLE_PRODUTO_SERVICO_.CODIGO = TABLE_DESPESA_VARIAVEL_.ID_PRODUTO_SERVICO
JOIN PUBLIC.TABLE_FONTE_PAGAMENTO TABLE_FONTE_PAGAMENTO_ ON TABLE_FONTE_PAGAMENTO_.CODIGO = TABLE_DESPESA_VARIAVEL_.ID_FONTE_PAGAMENTO
JOIN PUBLIC.TABLE_CANAL_PAGAMENTO TABLE_CANAL_PAGAMENTO_ ON TABLE_CANAL_PAGAMENTO_.CODIGO = TABLE_DESPESA_VARIAVEL_.ID_CANAL_PAGAMENTO
JOIN PUBLIC.TABLE_RESPONSAVEL_PAGAMENTO TABLE_RESPONSAVEL_PAGAMENTO_ ON TABLE_RESPONSAVEL_PAGAMENTO_.CODIGO = TABLE_DESPESA_VARIAVEL_.ID_RESPONSAVEL_PAGAMENTO
ORDER BY TABLE_DESPESA_VARIAVEL_.CODIGO ASC;

